#!/bin/sh

cd $(cd $(dirname $0); pwd)
vagrant destroy -f
./up

vagrant ssh -c 'curl -f https://raw.githubusercontent.com/mitchellh/vagrant/master/keys/vagrant.pub -o ~/.ssh/authorized_keys'
vagrant halt
[ -f package.box ] && rm package.box
vagrant package --base 'Android video-app dev env using Qt'
vagrant destroy -f

read -n 1 -s -p 'Press any key to re-import box. If you want stop, press CTRL+C'

# re-import for test
vagrant box add --name danmaq/openSUSE-42.1-x86_64-Android-Qt-videoapp-dev-env package.box
