#!/bin/sh

cd $(cd $(dirname $0); pwd)
lc_temp=.tmp
reload=${lc_temp}/.reboot
[ ! -d ${lc_temp} ] && mkdir ${lc_temp}
[ -f ${reload} ] && rm ${reload}

vagrant up --provision

while [ -f ${reload} ]
do
    echo 'Reloading...'
    rm ${reload}
    vagrant reload --provision
done
